const UPI_ID="8137082694@ptyes", WHATSAPP="918137082694";
let products=[], cart=JSON.parse(localStorage.getItem("styleAgainCart")||"[]"), wish=JSON.parse(localStorage.getItem("styleAgainWish")||"[]"), currentFilter="all";
const $=s=>document.querySelector(s);
function save(){localStorage.setItem("styleAgainCart",JSON.stringify(cart));localStorage.setItem("styleAgainWish",JSON.stringify(wish));updateCounts()}
function updateCounts(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);$("#wishCount").textContent=wish.length}
async function loadProducts(){try{let r=await fetch('/api/products');let d=await r.json();products=d.products||[];render()}catch(e){console.error(e);$("#productGrid").innerHTML='<p>Could not load products. Make sure the Flask server is running.</p>'}}
function render(filter="all"){currentFilter=filter;let list=filter==="all"?products:products.filter(p=>p.category===filter);$("#productGrid").innerHTML=list.map(p=>`<article class="card"><button class="heart" onclick="toggleWish(${p.id})">${wish.includes(p.id)?"♥":"♡"}</button><div class="photo product-photo" onclick="viewProduct(${p.id})" style="${p.image?`background-image:url('${p.image}')`:''}">${p.image?'':'<span>STYLE AGAIN</span>'}</div><div class="card-info"><h3>${p.name}</h3><div class="price">₹${Number(p.price).toLocaleString()} ${p.old_price?`<span class="old">₹${Number(p.old_price).toLocaleString()}</span>`:''}</div><div class="stock">${p.stock<=2&&p.stock>0?'Only '+p.stock+' left':p.stock===0?'Sold out':'In stock'}</div><button class="add" ${p.stock===0?'disabled':''} onclick="addToCart(${p.id})">${p.stock===0?'SOLD OUT':'ADD TO BAG'}</button></div></article>`).join('')||'<p>No products in this collection yet.</p>'}
function filterProducts(f,b){document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(f)}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];save();render(currentFilter)}
function addToCart(id,size){let p=products.find(x=>x.id===id);if(!p||p.stock<1)return;size=size||p.sizes?.[0]||'M';let x=cart.find(x=>x.id===id&&x.size===size);if(x)x.qty++;else cart.push({id,qty:1,size});save();showCart()}
function showCart(){openPanel(`<div class="panel-head"><h2>YOUR BAG</h2><button class="close" onclick="closePanel()">×</button></div>${cart.length?cart.map(x=>{let p=products.find(p=>p.id===x.id);if(!p)return '';return `<div class="cart-row"><div class="mini-photo" style="${p.image?`background-image:url('${p.image}')`:''}">${p.image?'':'V'}</div><div><b>${p.name}</b><br>Size: ${x.size}<br>₹${p.price}<br><div class="qty"><button onclick="changeQty(${x.id},${x.size?JSON.stringify(x.size):'null'},-1)">−</button> ${x.qty} <button onclick="changeQty(${x.id},${x.size?JSON.stringify(x.size):'null'},1)">+</button></div></div><button class="close" onclick="removeCart(${x.id},${JSON.stringify(x.size)})">×</button></div>`}).join('')+`<div class="total"><span>Total</span><span>₹${total()}</span></div><button class="green" onclick="checkout()">CHECKOUT</button>`:`<div class="success"><h2>Your bag is empty.</h2><a class="btn light" href="#shop" onclick="closePanel()">SHOP NOW</a></div>`}`)}
function total(){return cart.reduce((a,x)=>a+((products.find(p=>p.id===x.id)?.price||0)*x.qty),0)}
function changeQty(id,size,d){let x=cart.find(x=>x.id===id&&x.size===size);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>!(y.id===id&&y.size===size));save();showCart()}
function removeCart(id,size){cart=cart.filter(x=>!(x.id===id&&x.size===size));save();showCart()}
function checkout(){let sizeOptions=cart.length?cart[0].size:'';openPanel(`<div class="panel-head"><h2>CHECKOUT</h2><button class="close" onclick="closePanel()">×</button></div><p class="eyebrow">DELIVERY DETAILS</p><input class="field" id="name" placeholder="Full name"><input class="field" id="phone" placeholder="Phone number"><input class="field" id="email" placeholder="Email"><textarea class="field" id="address" placeholder="Full delivery address"></textarea><input class="field" id="pin" placeholder="PIN code"><p class="eyebrow">ORDER</p><div class="checkout-items">${cart.map(x=>{let p=products.find(p=>p.id===x.id);return `<div>${p.name} × ${x.qty} — Size ${x.size} — ₹${p.price*x.qty}</div>`}).join('')}</div><div class="paybox"><b>UPI PAYMENT</b><p>Pay exactly <b>₹${total()}</b> to <b>${UPI_ID}</b>.</p><button class="green" onclick="payUPI()">PAY WITH UPI</button></div><label class="confirm-check"><input type="checkbox" id="paidCheck"> I completed the payment and will send my Order ID + payment screenshot on WhatsApp.</label><button class="green" onclick="placeOrder()">PAYMENT COMPLETED — PLACE ORDER</button><p style="font-size:10px;color:#777">Payment is manually verified from your screenshot. This button does not independently verify bank payment.</p>`) }
function payUPI(){location.href=`upi://pay?pa=${encodeURIComponent(UPI_ID)}&pn=STYLE%20AGAIN&am=${total()}&cu=INR`}
async function placeOrder(){let name=$("#name")?.value.trim(),phone=$("#phone")?.value.trim(),email=$("#email")?.value.trim(),address=$("#address")?.value.trim(),pin=$("#pin")?.value.trim();if(!name||!phone||!address||!pin||!$('#paidCheck').checked){alert('Fill delivery details and confirm payment.');return}let order="STY"+Date.now().toString().slice(-8),items=cart.map(x=>{let p=products.find(p=>p.id===x.id);return `${p.name} x${x.qty} (Size ${x.size})`}).join(' | '),payload={order_id:order,name,phone,email,address,pin,items,size:cart.map(x=>x.size).join(', '),total:total()};try{let r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw 0}catch(e){alert('Could not save the order. Make sure the Flask server is running.');return}let msg=`Hi STYLE AGAIN, I have paid for Order ID ${order}. I am sending my payment screenshot for confirmation.`;cart=[];save();openPanel(`<div class="success"><p class="eyebrow">THANK YOU</p><h1>ORDER PLACED<br>SUCCESSFULLY</h1><p><b>ORDER ID: ${order}</b></p><p>WHATSAPP NUMBER: 8137082694</p><p>SEND THE ORDER ID AND PAYMENT SCREENSHOT IN WHATSAPP FOR CONFIRMATION.</p><a class="wa" target="_blank" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}">SEND ON WHATSAPP</a><button class="green" style="margin-top:10px" onclick="showOrders()">VIEW MY ORDERS</button></div>`)}
async function showOrders(){let phone=prompt('Enter the phone number used for your order:');if(!phone)return;let r=await fetch('/api/orders?phone='+encodeURIComponent(phone)),d=await r.json();openPanel(`<div class="panel-head"><h2>MY ORDERS</h2><button class="close" onclick="closePanel()">×</button></div>${d.orders.length?d.orders.map(o=>`<div class="order-card"><b>${o.order_id}</b><span>${new Date(o.created_at).toLocaleString()}</span><p>${o.items}</p><p>Total: <b>₹${Number(o.total).toLocaleString()}</b></p><p>Status: <b>${o.status}</b></p></div>`).join(''):'<p>No orders found for this phone number.</p>'}`)}
function openPanel(html){$("#panel").innerHTML=html;$("#overlay").classList.add('open')}
function closePanel(e){if(!e||e.target===$("#overlay"))$("#overlay").classList.remove('open')}
function showWishlist(){let list=products.filter(p=>wish.includes(p.id));openPanel(`<div class="panel-head"><h2>WISHLIST</h2><button class="close" onclick="closePanel()">×</button></div>${list.length?list.map(p=>`<div class="cart-row"><div class="mini-photo" style="${p.image?`background-image:url('${p.image}')`:''}">${p.image?'':'V'}</div><div><b>${p.name}</b><br>₹${p.price}</div><button onclick="addToCart(${p.id})">+</button></div>`).join(''):'<p>Your wishlist is empty.</p>'}`)}
function openSearch(){openPanel(`<div class="panel-head"><h2>SEARCH</h2><button class="close" onclick="closePanel()">×</button></div><input class="field" autofocus placeholder="Search products..." oninput="search(this.value)"><div id="results"></div>`)}
function search(q){let l=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase()));$("#results").innerHTML=l.map(p=>`<div class="cart-row"><div class="mini-photo" style="${p.image?`background-image:url('${p.image}')`:''}">${p.image?'':'V'}</div><div><b>${p.name}</b><br>₹${p.price}</div><button onclick="addToCart(${p.id})">+</button></div>`).join('')}
function openFilters(){openPanel(`<div class="panel-head"><h2>FILTERS</h2><button class="close" onclick="closePanel()">×</button></div><p class="eyebrow">CATEGORY</p>${['all','T-Shirts','Hoodies','Jackets','Pants'].map(x=>`<button class="btn" style="border:1px solid #ccc;background:none;margin:5px" onclick="closePanel();render('${x}')">${x}</button>`).join('')}`)}
function viewProduct(id){let p=products.find(p=>p.id===id);if(!p)return;let sizes=p.sizes?.length?p.sizes:['M'];openPanel(`<div class="panel-head"><h2>${p.name}</h2><button class="close" onclick="closePanel()">×</button></div><div class="photo product-detail-photo" style="margin:20px 0;${p.image?`background-image:url('${p.image}')`:''}">${p.image?'':'<span>STYLE AGAIN</span>'}</div><p class="price">₹${p.price} ${p.old_price?`<span class="old">₹${p.old_price}</span>`:''}</p><p><b>Condition:</b> ${p.condition||'9/10'}</p><p>${p.description||'Curated thrift piece. Condition checked before dispatch.'}</p><p><b>Size</b></p><div class="size-pills">${sizes.map(s=>`<button onclick="addToCart(${p.id},${JSON.stringify(s)})">${s}</button>`).join('')}</div><p class="stock">${p.stock} available</p>`)}
loadProducts();updateCounts();
